### ISSUE TITLE
Usage with babel plugin

### ISSUE THREAD

**Issue by JiDai** [DoumanAsh/fuse-box-eslint-plugin#1]
Hi

I have a config that use babel plugin (for React)
I install these plugins : 

```
    "eslint-plugin-babel": "3.3.0",
    "eslint-plugin-react": "6.5.0",
```

And this is my config : 

```
    plugins: [
        eslinter({
            pattern: /js(x)*$/,
            eslint: {
                configFile: '.eslintrc'
            }
        }),
        ...
```

When I launch Fuse server I got an error on spread notation : 

```
137          combineReducers({
138              ...reducers,
139              routing: routerReducer,
```

Thanks!

**Comment by DoumanAsh** [comment]
I suspect it is because of the way you configured your `configFile`

If it doesn't exist it will be null, but i suppose i should also give warning.
I will re-check it.

Meanwhile, you can work around it by removing setting of this option and renaming your file to `.eslintrc.js`
Plugin will assumes as default `<root>/.eslintrc.js`

**UPD:**: No, im mistaken, if file wouldn't exist it would throw error... can you please share your project, so that i could take a look?

**Comment by JiDai** [comment]
I try to use `.eslintrc.js` and the line `fs.existsSync(eslint_defaults.configFile)` return true. 
So I suppose my config is used but I still have this error.
I also try so run aslant manually an it works

**Comment by DoumanAsh** [comment]
Can you please also share your `.eslintrc` config?
I just tried out to test it and there is no error on spread :(

I also would like to see full error

**Comment by JiDai** [comment]
Yep : 

```
module.exports = {
    // Extend existing configuration
    // from ESlint and eslint-plugin-react defaults.
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    // In order to use Babel features
    // you need to enable this custom parser
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "env": {
        "browser": true,
        "node": true,
        "mocha": true
    },
    "globals": {
        "Promise": true,
        "MA": true,
        "google": true,
        "DocumentTouch": true,
        "FS": true,
        "UserVoice": true
    },
    // Enable custom plugin known as eslint-plugin-react
    "plugins": [
        "babel",
        "react"
    ],
    "rules": {
        // Disable `no-console` rule
        "no-console": 2,
        "no-alert": 2,
        "no-debugger": 2,
        // Give a warning if identifiers contain underscores
        "no-underscore-dangle": 2,
        // Default to single quotes and raise an error if something
        // else is used
        "quotes": [
            2,
            "single"
        ],
        "no-multiple-empty-lines": [
            "error",
            {
                "max": 2
            }
        ],
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1
            }
        ],
        "react/jsx-indent": [
            "error",
            4
        ],
        "react/jsx-indent-props": [
            "error",
            4
        ],
        "react/prop-types": [
            1,
            {
                "ignore": [
                    "children",
                    "dispatch",
                    "params"
                ]
            }
        ],
        "semi": [
            2,
            "never"
        ],
        "max-len": [
            0,
            180,
            2
        ],
        "generator-star-spacing": 0,
        "babel/generator-star-spacing": 1
    }
}
```

**Comment by DoumanAsh** [comment]
Hm... it is rather strange that it doesn't throw error when you haven't specified `env.es6 = true` or `ecmaVersion` in `parserOptions`
If possible it would be faster if i could take a look at your project and try to debug it on my own?

**Comment by JiDai** [comment]
I can't it's a private project, but I tried on another project with similar environement on this branch :
https://github.com/JiDai/basic-hot-reload/tree/fusebox-eslint

Manual command Eslint find one error : ` 20:13  error  'i' is assigned a value but never used  no-unused-vars`
Eslint plugin fail on syntax error on `static` property, but find the eslint error : 

```
/Users/jd/GitHome/basic-hot-reload/src/index.js
  20:13  error  'i' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

Acorn error: Unexpected token (10:21)
File: /Users/jd/GitHome/basic-hot-reload/src/containers/Root.js

8
9  export default class Root extends Component {
10      static propTypes = {
11          store: PropTypes.object
12      }
13
14      constructor (props) {
```

**Comment by DoumanAsh** [comment]
Thanks, i'll take a look

**Comment by DoumanAsh** [comment]
It seems rather bizarre but i don't see issue in plugin itself, but maybe there is some difference between eslint actual cli and `CLIengine`.
I will need to take a look at eslint sources for that i suspect. I'll keep you posted.

**Comment by JiDai** [comment]
Thanks!

**Comment by DoumanAsh** [comment]
Ok, it turns out that error is actually coming not from `eslint`.

**UPD**: i actually cannot pinpoint when error happens, but it doesn't happen when we parse with `eslint` :(

**Comment by DoumanAsh** [comment]
Frankly i have no idea what is source of issue.
The only thing i understand is that when you have my plugin, for some reason other plugin that parses javascript code is failing (most likely Babel).
But i do not understand how is it possible as `eslinter` isn't modifying sources at all. And well i dunno how it can affect `babel` plugin.

**Comment by JiDai** [comment]
I have the feeling that babel do not get the config in `.babelrc` or fuse config because it fail on line  normally handle by preset `react`

**Comment by DoumanAsh** [comment]
But i don't have explanation of how it is related to `eslinter` :(
Because if i remove it, and i think i also removed `stage-0` preset, babel works ok.

**Comment by JiDai** [comment]
Hi,
When I use your plugin, execution pas on this [line](https://github.com/fuse-box/fuse-box/blob/master/src/analysis/FileAnalysis.ts#L85) and the file contents is source file (JSX) but when I remove the plugin the code is transpiled.
Do you know why ?

**Comment by DoumanAsh** [comment]
Hm... i don't understand why, file content should not be modified. I'm guessing here, but maybe order of plugins is important?
Could you maybe share your current plugin setup

**Comment by JiDai** [comment]
Here it is  : 

```

const fuseBox = new fsbx.FuseBox({
    homeDir: "src/",
    sourcemaps: {
        bundleReference: "sourcemaps.js.map",
        outFile: "./build/sourcemaps.js.map",
    },
    outFile: "./build/bundle.js",
    plugins: [
        eslinter({
            pattern: /js(x)*$/,
        }),
        [
            fsbx.SassPlugin(),
            fsbx.CSSResourcePlugin({ inline: true }),
            fsbx.CSSPlugin()
        ],
        fsbx.EnvPlugin(env),
        fsbx.BabelPlugin()
    ]
});

fuseBox.devServer("> index.js");
```

**Comment by DoumanAsh** [comment]
Hm... that's strange. I don't really understand right now what can be wrong.
And im not using fuse-box now. I will need to take a look at recent changes in plugin API.

**Comment by JiDai** [comment]
Ha! I finally make it works.

By using this config and chaining aslant with babel : 

```
const fuseBox = new fsbx.FuseBox({
    homeDir: "src/",
    debug: false,
    sourcemaps: {
        bundleReference: "sourcemaps.js.map",
        outFile: "./build/sourcemaps.js.map",
    },
    outFile: "./build/bundle.js",
    plugins: [
        [
            fsbx.SassPlugin(),
            fsbx.CSSResourcePlugin({ inline: true }),
            fsbx.CSSPlugin()
        ],
        fsbx.EnvPlugin(env),
        [
            eslinter({
                pattern: /js(x)*$/,
            }),
            fsbx.BabelPlugin(),
        ]
    ]
});
```

**Comment by DoumanAsh** [comment]
Glad to hear that, but i'm not sure what could cause such issue in first place :(

**Comment by ausir0726** [comment]
thanks @JiDai 

this config you suggest is working.
```
const fuse = fsbx.FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
    plugins: [
      fsbx.JSONPlugin(),
      [
        eslinter(),
        fsbx.BabelPlugin({
          presets: ["latest"]
        })
      ],
    ],
});
```

**Comment by JiDai** [comment]
For information, I tried this same plugin configuration with Fuse-box 2.4 and it is not working. I have multiple error like : 
```
AssertionError [ERR_ASSERTION]: ImportDeclaration should appear when the mode is ES6 and in the module context.
    at Referencer.ImportDeclaration (/Users/jd/GitHome/basic-hot-reload/node_modules/escope/lib/referencer.js:591:34)
    at Referencer.Visitor.visit (/Users/jd/GitHome/basic-hot-reload/node_modules/esrecurse/esrecurse.js:122:34)
    at Referencer.Visitor.visitChildren (/Users/jd/GitHome/basic-hot-reload/node_modules/esrecurse/esrecurse.js:101:38)
    at Referencer.Program (/Users/jd/GitHome/basic-hot-reload/node_modules/escope/lib/referencer.js:419:18)
    at Referencer.Visitor.visit (/Users/jd/GitHome/basic-hot-reload/node_modules/esrecurse/esrecurse.js:122:34)
    at Object.analyze (/Users/jd/GitHome/basic-hot-reload/node_modules/escope/lib/index.js:153:16)
    at EventEmitter.module.exports.api.verify (/Users/jd/GitHome/basic-hot-reload/node_modules/fuse-box-eslint-plugin/node_modules/eslint/lib/eslint.js:892:35)
    at processText (/Users/jd/GitHome/basic-hot-reload/node_modules/fuse-box-eslint-plugin/node_modules/eslint/lib/cli-engine.js:264:31)
    at CLIEngine.executeOnText (/Users/jd/GitHome/basic-hot-reload/node_modules/fuse-box-eslint-plugin/node_modules/eslint/lib/cli-engine.js:754:26)
    at ESLinter.transform (/Users/jd/GitHome/basic-hot-reload/node_modules/fuse-box-eslint-plugin/src/index.js:64:39)```

**Comment by DoumanAsh** [comment]
I'm sorry I'm currently not really into front-end developement so I don't really follow up what's going on
